### ISSUE TITLE
Cannot delete or update a business

### ISSUE THREAD

**Issue by ahalliop** [truckerswelcome/webapp#41]
I created a new entry for Halifax yesterday via testuser, but I can't seem to delete it or update it.
I see this error: Uncaught TypeError: Cannot read property 'length' of undefined
    at XMLHttpRequest.xhr.onreadystatechange (tw.js:110)

But I don't see any errors on the page or any highlighted unfilled in items.

I'm on my macbook (high sierra, chrome browser)

**Comment by tyler-reese** [comment]
Can you see the JSON response that comes back for this request?

**Comment by domcho** [comment]
Some input on this in addition to whatever the fix will be:

- Errors should be more obvious for the user. It's especially bad on mobile because you have to scroll back up to the top of the page
- In general I think we need some better error handling & response on the client side. Would it even make sense to retry depending on the error? We do have networking issues...
- Errors on the server side should be logged using syslog() so we can debug. Maybe even post to the slack support channel so we are aware

**Comment by domcho** [comment]
Verified fixed while adding entries
